[package]
name = "nostd"
edition = "2024"

[dependencies]
bitflags = { version = "2.10.0", features = ["serde"] } 
serde = { version = "1.0.219", features = ["derive"] }
serde-big-array = "0.5.1"
serde_json = "1.0.140"
